### ISSUE TITLE
Review Footer design

### ISSUE THREAD

**Issue by AndresHense** [alkemyTech/OT139-CLIENT#52]
* achicar el fontSize
* achicar el height del footer
* tirar el footer abajo de todo con algo como
```css
.footer{
   position: absolute;
   bottom: 0;
}
```
